@AuthDemo_HostAddress = http://localhost:5132

GET {{AuthDemo_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{AuthDemo_HostAddress}}/TodoItems
Accept: application/json

###
